import fs from 'fs';
import path from 'path';

import { GROUPS_DIR } from '../config.js';
import { logger } from '../logger.js';
import { listProcedures, type Procedure } from '../memory/procedure-store.js';

export interface ExportOptions {
  topN?: number;
  minRuns?: number;
  groupId?: string;
}

const DEFAULT_TOP_N = 20;
const DEFAULT_MIN_RUNS = 1;

function totalRuns(p: Procedure): number {
  return p.success_count + p.failure_count;
}

function score(p: Procedure): number {
  // Penalize failures harder than successes credit. Tiebreaks by total runs.
  return p.success_count - 2 * p.failure_count;
}

export function rankProcedures(
  procs: Procedure[],
  opts: { topN?: number; minRuns?: number } = {},
): Procedure[] {
  const topN = opts.topN ?? DEFAULT_TOP_N;
  const minRuns = opts.minRuns ?? DEFAULT_MIN_RUNS;
  return procs
    .filter((p) => totalRuns(p) >= minRuns)
    .sort((a, b) => {
      const ds = score(b) - score(a);
      if (ds !== 0) return ds;
      return totalRuns(b) - totalRuns(a);
    })
    .slice(0, topN);
}

export function exportProceduresMarkdown(opts: ExportOptions = {}): string {
  const ranked = rankProcedures(listProcedures(opts.groupId), opts);
  const today = new Date().toISOString().slice(0, 10);

  if (ranked.length === 0) {
    return `# Learned Procedures\n\n_No procedures recorded yet (${today})._\n`;
  }

  const lines: string[] = [
    '# Learned Procedures',
    '',
    `_Top ${ranked.length} procedures by success rate (generated ${today})_`,
    '',
    '<!-- Auto-generated by scripts/learning-export-md.ts. Do not edit. -->',
    '',
  ];

  for (const p of ranked) {
    const total = totalRuns(p);
    const rate = total > 0 ? Math.round((p.success_count / total) * 100) : 0;
    const auto = p.auto_execute ? ' _(auto)_' : '';
    lines.push(`## ${p.name}${auto}`);
    lines.push('');
    lines.push(`- **Trigger:** \`${p.trigger}\``);
    lines.push(
      `- **Stats:** ${rate}% success across ${total} runs (${p.success_count}✓ / ${p.failure_count}✗)`,
    );
    if (p.description) {
      lines.push(`- **Description:** ${p.description}`);
    }
    lines.push('');
    lines.push('Steps:');
    p.steps.forEach((s, i) => {
      const detail = s.details ? ` — ${s.details}` : '';
      lines.push(`${i + 1}. \`${s.action}\`${detail}`);
    });
    lines.push('');
  }

  return lines.join('\n');
}

export function writeProceduresMarkdown(
  groupId: string,
  opts: Omit<ExportOptions, 'groupId'> = {},
): string {
  const md = exportProceduresMarkdown({ ...opts, groupId });
  const filePath = path.join(GROUPS_DIR, groupId, 'PROCEDURES.md');
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, md, 'utf-8');
  logger.info(
    { groupId, filePath, bytes: md.length },
    'Wrote procedures markdown',
  );
  return filePath;
}
