import fs from 'fs';
import path from 'path';

import { GROUPS_DIR } from '../config.js';
import { logger } from '../logger.js';
import { listProcedures, type Procedure } from '../memory/procedure-store.js';

export interface ExportOptions {
  topN?: number;
  minRuns?: number;
  groupId?: string;
}

const DEFAULT_TOP_N = 20;
const DEFAULT_MIN_RUNS = 1;

function totalRuns(p: Procedure): number {
  return p.success_count + p.failure_count;
}

function score(p: Procedure): number {
  // Penalize failures harder than successes credit. Tiebreaks by total runs.
  return p.success_count - 2 * p.failure_count;
}

export function rankProcedures(
  procs: Procedure[],
  opts: { topN?: number; minRuns?: number } = {},
): Procedure[] {
  const topN = opts.topN ?? DEFAULT_TOP_N;
  const minRuns = opts.minRuns ?? DEFAULT_MIN_RUNS;
  return procs
    .filter((p) => totalRuns(p) >= minRuns)
    .sort((a, b) => {
      const ds = score(b) - score(a);
      if (ds !== 0) return ds;
      return totalRuns(b) - totalRuns(a);
    })
    .slice(0, topN);
}

export function exportProceduresMarkdown(opts: ExportOptions = {}): string {
  const ranked = rankProcedures(listProcedures(opts.groupId), opts);
  const today = new Date().toISOString().slice(0, 10);

  if (ranked.length === 0) {
    return `# Learned Procedures\n\n_No procedures recorded yet (${today})._\n`;
  }

  const lines: string[] = [
    '# Learned Procedures',
    '',
    `_Top ${ranked.length} procedures by success rate (generated ${today})_`,
    '',
    '<!-- Auto-generated by scripts/learning-export-md.ts. Do not edit. -->',
    '',
  ];

  for (const p of ranked) {
    const total = totalRuns(p);
    const rate = total > 0 ? Math.round((p.success_count / total) * 100) : 0;
    const auto = p.auto_execute ? ' _(auto)_' : '';
    lines.push(`## ${p.name}${auto}`);
    lines.push('');
    lines.push(`- **Trigger:** \`${p.trigger}\``);
    lines.push(
      `- **Stats:** ${rate}% success across ${total} runs (${p.success_count}✓ / ${p.failure_count}✗)`,
    );
    if (p.description) {
      lines.push(`- **Description:** ${p.description}`);
    }
    lines.push('');
    lines.push('Steps:');
    p.steps.forEach((s, i) => {
      const detail = s.details ? ` — ${s.details}` : '';
      lines.push(`${i + 1}. \`${s.action}\`${detail}`);
    });
    lines.push('');
  }

  return lines.join('\n');
}

export function writeProceduresMarkdown(
  groupId: string,
  opts: Omit<ExportOptions, 'groupId'> = {},
): string {
  const md = exportProceduresMarkdown({ ...opts, groupId });
  const filePath = path.join(GROUPS_DIR, groupId, 'PROCEDURES.md');
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, md, 'utf-8');
  logger.info(
    { groupId, filePath, bytes: md.length },
    'Wrote procedures markdown',
  );
  return filePath;
}

/**
 * Discover every group with at least one non-deprecated procedure on disk
 * and return its folder name. Independent of registered-group state so the
 * scheduler doesn't depend on JID/folder normalization.
 */
export function discoverGroupsWithProcedures(): string[] {
  if (!fs.existsSync(GROUPS_DIR)) return [];
  const found: string[] = [];
  for (const entry of fs.readdirSync(GROUPS_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const procDir = path.join(GROUPS_DIR, entry.name, 'procedures');
    if (!fs.existsSync(procDir)) continue;
    const hasActive = fs
      .readdirSync(procDir)
      .some((f) => f.endsWith('.json') && !f.endsWith('.deprecated.json'));
    if (hasActive) found.push(entry.name);
  }
  return found;
}

export interface WriteAllResult {
  written: { groupId: string; filePath: string }[];
  failed: { groupId: string; error: string }[];
}

/**
 * Write PROCEDURES.md for every group with active procedures. Errors per
 * group are caught and reported, never thrown — one bad group must not stop
 * the rest.
 */
export function writeAllProceduresMarkdown(
  opts: Omit<ExportOptions, 'groupId'> = {},
): WriteAllResult {
  const result: WriteAllResult = { written: [], failed: [] };
  for (const groupId of discoverGroupsWithProcedures()) {
    try {
      const filePath = writeProceduresMarkdown(groupId, opts);
      result.written.push({ groupId, filePath });
    } catch (err) {
      result.failed.push({
        groupId,
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }
  return result;
}

export interface ScheduleOptions {
  intervalMs?: number;
  runImmediately?: boolean;
  exportOpts?: Omit<ExportOptions, 'groupId'>;
}

const DEFAULT_INTERVAL_MS = 24 * 60 * 60 * 1000;

/**
 * Start a recurring writer. Returns a stop() function for tests + graceful
 * shutdown. Errors inside the callback are logged, never propagated, so the
 * timer keeps firing.
 */
export function startProceduresMarkdownSchedule(
  opts: ScheduleOptions = {},
): () => void {
  const intervalMs = opts.intervalMs ?? DEFAULT_INTERVAL_MS;

  const tick = (): void => {
    try {
      const r = writeAllProceduresMarkdown(opts.exportOpts);
      if (r.written.length > 0 || r.failed.length > 0) {
        logger.info(
          { written: r.written.length, failed: r.failed.length },
          'PROCEDURES.md schedule tick',
        );
      }
      for (const f of r.failed) {
        logger.warn(f, 'PROCEDURES.md export failed for group');
      }
    } catch (err) {
      logger.warn(
        { err: err instanceof Error ? err.message : String(err) },
        'PROCEDURES.md schedule tick failed',
      );
    }
  };

  if (opts.runImmediately !== false) tick();
  const handle = setInterval(tick, intervalMs);
  return () => clearInterval(handle);
}
